apiVersion: v1
kind: Pod
metadata: 
  name: volume-demo-pod
spec:
  containers:
    - name: nginx-container 
      image: nginx
      volumeMounts: 
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: config-volume 
      configMap: 
        name: demo-config

    - name: secret-volume
      secret: 
        secretName: demo-secret