version: "3.8"

services:
  app1:
    image: ubuntu
    container_name: container1
    tty: true
    volumes: 
      - shared_volume:/data
  
  app2:
    image: ubuntu
    container_name: container2
    tty: true
    volumes: 
      - shared_volume:/data

volumes:
  shared_volume: {}