name: Simple Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Runner
        run: echo "Self-hosted runner is working!"

  deploy-production:
    needs: test
    runs-on: self-hosted
    environment: production

    steps:
      - name: Production Deploy Step
        run: echo "Deploying to production..."
